# Generated by Django 5.0.6 on 2026-06-16 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_deleted'], name='blog_blogpo_is_dele_e31fa5_idx'),
        ),
    ]
