# Generated by Django 5.0.6 on 2026-06-29 05:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_is_deleted_and_more'),
        ('products', '0002_stockmovement_supplier_and_more'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts_m2m', to='blog.blogcategory'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='quality_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='products.product'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_services',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='services.service'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags_json',
            field=models.JSONField(blank=True, default=list, help_text='Legacy JSON tags. Use the tags ManyToMany relationship going forward.'),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.CreateModel(
            name='BlogGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(help_text='scheduler or admin', max_length=20)),
                ('topic_used', models.TextField()),
                ('tokens_used', models.PositiveIntegerField()),
                ('quality_score', models.PositiveIntegerField()),
                ('retries', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_log', models.TextField(blank=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_logs', to='blog.blogpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('doc_type', models.CharField(choices=[('datasheet', 'Product Data Sheet'), ('iso_guide', 'ISO Standard Guide'), ('kebs_guide', 'KEBS Compliance Guide'), ('iec_guide', 'IEC Standard Guide'), ('case_study', 'Case Study'), ('whitepaper', 'Technical Whitepaper')], max_length=30)),
                ('standard_code', models.CharField(blank=True, help_text='e.g. ISO 9001:2015, KEBS KS 04-136, IEC 60204-1', max_length=50)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('excerpt', models.TextField(max_length=300)),
                ('body_html', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='tech-docs/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('related_blogs', models.ManyToManyField(blank=True, related_name='technical_documents', to='blog.blogpost')),
                ('related_products', models.ManyToManyField(blank=True, related_name='technical_documents', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_docs',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='blog.technicaldocument'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status'], name='blog_blogpo_status_9c1956_idx'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag'),
        ),
        migrations.AddIndex(
            model_name='technicaldocument',
            index=models.Index(fields=['slug'], name='blog_techni_slug_eef55b_idx'),
        ),
        migrations.AddIndex(
            model_name='technicaldocument',
            index=models.Index(fields=['doc_type'], name='blog_techni_doc_typ_7d689c_idx'),
        ),
        migrations.AddIndex(
            model_name='technicaldocument',
            index=models.Index(fields=['is_published'], name='blog_techni_is_publ_0777f7_idx'),
        ),
    ]
