# Generated by Django 5.0.6 on 2026-05-24 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=120, unique=True)),
                ('user_identifier', models.CharField(blank=True, max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('source_page', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetSyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sheet_name', models.CharField(max_length=120)),
                ('resource', models.CharField(max_length=120)),
                ('spreadsheet_id', models.CharField(blank=True, max_length=255)),
                ('last_pull_at', models.DateTimeField(blank=True, null=True)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(default='pending', max_length=40)),
                ('last_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['resource', 'sheet_name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_path', models.CharField(default='/', max_length=255)),
                ('performance_score', models.PositiveSmallIntegerField(default=0)),
                ('seo_score', models.PositiveSmallIntegerField(default=0)),
                ('accessibility_score', models.PositiveSmallIntegerField(default=0)),
                ('best_practices_score', models.PositiveSmallIntegerField(default=0)),
                ('largest_contentful_paint', models.FloatField(default=0)),
                ('first_contentful_paint', models.FloatField(default=0)),
                ('interaction_to_next_paint', models.FloatField(default=0)),
                ('cumulative_layout_shift', models.FloatField(default=0)),
                ('server_response_time', models.FloatField(default=0)),
                ('image_optimization_status', models.CharField(default='unknown', max_length=80)),
                ('caching_status', models.CharField(default='unknown', max_length=80)),
                ('broken_links', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeoPageMeta',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('page_path', models.CharField(max_length=255, unique=True)),
                ('page_label', models.CharField(max_length=120)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('og_title', models.CharField(blank=True, max_length=95)),
                ('og_description', models.CharField(blank=True, max_length=220)),
                ('og_image', models.CharField(blank=True, max_length=500)),
                ('canonical_url', models.CharField(blank=True, max_length=500)),
                ('index', models.BooleanField(default=True)),
                ('follow', models.BooleanField(default=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('schema_type', models.CharField(default='WebPage', max_length=80)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page_path'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('key', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=160)),
                ('value', models.TextField(blank=True)),
                ('type', models.CharField(default='text', max_length=30)),
                ('group', models.CharField(default='general', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'label'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('product_slug', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='operations.chatconversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
