# Generated by Django 5.0.6 on 2026-05-29 04:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Source URL that was scraped', max_length=500, unique=True)),
                ('page_label', models.CharField(help_text='Human-readable label, e.g. "Homepage", "Products"', max_length=120)),
                ('content', models.TextField(help_text='Extracted plain-text content from the page')),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Knowledge Cache Entry',
                'verbose_name_plural': 'Knowledge Cache',
                'ordering': ['page_label'],
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='escalated_to_whatsapp',
            field=models.BooleanField(default=False, help_text='True when a WhatsApp escalation CTA was sent'),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='lead_intent',
            field=models.BooleanField(default=False, help_text='True when visitor expressed quote/price/order intent'),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='product_interest',
            field=models.CharField(blank=True, help_text='Most recently mentioned product keyword', max_length=255),
        ),
    ]
