# Generated by Django 5.0.6 on 2026-05-24 13:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('product', 'Product Inquiry'), ('quote', 'Quote Request'), ('partnership', 'Partnership'), ('technical', 'Technical Support'), ('complaint', 'Complaint')], default='general', max_length=20)),
                ('product_interest', models.CharField(blank=True, help_text='Product name or category the inquiry is about', max_length=255)),
                ('quantity', models.CharField(blank=True, help_text='Estimated quantity needed', max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('processing', 'Processing'), ('replied', 'Replied'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('page_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='inquiries_i_status_152cc6_idx'), models.Index(fields=['email'], name='inquiries_i_email_415ef2_idx')],
            },
        ),
    ]
