# Generated by Django 5.0.6 on 2026-06-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='page_url',
            new_name='source_page',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='product_interest',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='autoreply_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='error_log',
            field=models.TextField(blank=True, help_text='Logs of any email sending failures'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='notification_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='ticket_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('quote', 'Quote Request'), ('product', 'Product Inquiry'), ('general', 'General Inquiry'), ('consultation', 'Consultation Request'), ('product_info', 'Product Information Request'), ('partnership', 'Distribution / Partnership'), ('technical', 'Technical Support')], db_index=True, default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('replied', 'Replied'), ('quotation_sent', 'Quotation Sent'), ('closed', 'Closed')], db_index=True, default='new', max_length=30),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['ticket_number'], name='inquiries_i_ticket__c00c13_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['inquiry_type'], name='inquiries_i_inquiry_398cb3_idx'),
        ),
    ]
