# Generated by Django 5.0.6 on 2026-06-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_rename_page_url_inquiry_source_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='product_name',
            field=models.CharField(blank=True, db_index=True, help_text='Product name or category the inquiry is about', max_length=255),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='ticket_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
