# Generated by Django 5.0.6 on 2026-06-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_alter_inquiry_name_alter_inquiry_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='referrer',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='source_page',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
