# Generated by Django 5.0.6 on 2026-05-24 13:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=100)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='industries/')),
                ('challenges', models.JSONField(blank=True, default=list, help_text='Industry challenges Zenco solves')),
                ('solutions', models.JSONField(blank=True, default=list, help_text='Zenco solutions for this industry')),
                ('relevant_products', models.JSONField(blank=True, default=list, help_text='List of related product slugs')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
