export const appConfig = {
  siteUrl: (process.env.NEXT_PUBLIC_SITE_URL || '').replace(/\/$/, ''),
  apiUrl: (process.env.NEXT_PUBLIC_API_URL || '').replace(/\/$/, ''),
  companyName: process.env.NEXT_PUBLIC_COMPANY_NAME || '',
  companyDivision: process.env.NEXT_PUBLIC_COMPANY_DIVISION || '',
  companyFullName: process.env.NEXT_PUBLIC_COMPANY_FULL_NAME || '',
  companyTagline: process.env.NEXT_PUBLIC_COMPANY_TAGLINE || '',
  companyDescription: process.env.NEXT_PUBLIC_COMPANY_DESCRIPTION || '',
  whatsappNumber: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '',
  phoneNumber: process.env.NEXT_PUBLIC_PHONE_NUMBER || '',
  companyEmail: process.env.NEXT_PUBLIC_COMPANY_EMAIL || '',
  streetAddress: process.env.NEXT_PUBLIC_COMPANY_STREET_ADDRESS || '',
  city: process.env.NEXT_PUBLIC_COMPANY_CITY || '',
  country: process.env.NEXT_PUBLIC_COMPANY_COUNTRY || '',
  postalCode: process.env.NEXT_PUBLIC_COMPANY_POSTAL_CODE || '',
  openingHours: process.env.NEXT_PUBLIC_COMPANY_OPENING_HOURS || '',
  serviceArea: process.env.NEXT_PUBLIC_SERVICE_AREA || '',
  locale: process.env.NEXT_PUBLIC_LOCALE || '',
  timeZone: process.env.NEXT_PUBLIC_TIME_ZONE || '',
  currency: process.env.NEXT_PUBLIC_CURRENCY || '',
  acceptedCurrencies: process.env.NEXT_PUBLIC_ACCEPTED_CURRENCIES || '',
  latitude: process.env.NEXT_PUBLIC_COMPANY_LATITUDE || '',
  longitude: process.env.NEXT_PUBLIC_COMPANY_LONGITUDE || '',
  googleMapsPlaceQuery: process.env.NEXT_PUBLIC_GOOGLE_MAPS_PLACE_QUERY || '',
  googleMapsEmbedKey: process.env.NEXT_PUBLIC_GOOGLE_MAPS_EMBED_KEY || '',
  linkedinUrl: process.env.NEXT_PUBLIC_LINKEDIN_URL || '',
  instagramUrl: process.env.NEXT_PUBLIC_INSTAGRAM_URL || '',
  facebookUrl: process.env.NEXT_PUBLIC_FACEBOOK_URL || '',
  tiktokUrl: process.env.NEXT_PUBLIC_TIKTOK_URL || '',
  twitterUrl: process.env.NEXT_PUBLIC_TWITTER_URL || '',
  twitterHandle: process.env.NEXT_PUBLIC_TWITTER_HANDLE || '',
  defaultKeywords: process.env.NEXT_PUBLIC_DEFAULT_KEYWORDS || '',
} as const
