# Generated by Django 5.0.6 on 2026-05-24 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='{"CAS Number": "64-17-5", "Purity": "99.5%", ...}')),
                ('applications', models.JSONField(blank=True, default=list, help_text='["Cleaning", "Industrial solvent", ...]')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('gallery', models.JSONField(blank=True, default=list, help_text='List of additional image URLs')),
                ('datasheet', models.FileField(blank=True, help_text='Product technical datasheet PDF', null=True, upload_to='datasheets/')),
                ('packaging', models.CharField(blank=True, max_length=255)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_currency', models.CharField(default='KES', max_length=8)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='units', max_length=50)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('supplier_name', models.CharField(blank=True, max_length=180)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('availability', models.CharField(choices=[('in_stock', 'In Stock'), ('limited', 'Limited Stock'), ('out_of_stock', 'Out of Stock'), ('on_order', 'Available on Order')], default='in_stock', max_length=20)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], default='published', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('schema_data', models.JSONField(blank=True, default=dict, help_text='Additional schema.org structured data overrides')),
                ('regions_available', models.JSONField(blank=True, default=list, help_text='["Kenya", "Uganda", "Tanzania", "East Africa"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'), models.Index(fields=['is_featured', 'is_active'], name='products_pr_is_feat_a1ecf6_idx'), models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx')],
            },
        ),
    ]
