# Generated by Django 5.0.6 on 2026-07-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stockmovement_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content_sections',
            field=models.JSONField(blank=True, default=dict, help_text='AI-generated authority page content: introduction, industry_applications, buying_guide, selection_criteria, faq_section'),
        ),
    ]
